sudo: false
language: node_js
node_js:
  - 'node'

dist: xenial
os: 
 - windows
 - osx

cache:
  directories:
  - node_modules

before_install:
- cd src
- npm update

install:
  - npm install

script:
  - npm test
  - codecov