sudo: false
language: node_js
node_js:
  - 'node'
os:
  - osx
  - linux
dist: xenial


before_install:
  - cd src

addons:
  homebrew:
    packages:
      - wine

  apt:
    packages:
      - xvfb
      - wine

install:
  - export DISPLAY=':99.0'
  - xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm i
  - npm i electron-packager

script:
  - echo $PATH
  - npm test
  - npm run build

after_success:
  - codecov

env:
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"