sudo: false
language: node_js
node_js:
  - "node"
os:
  - osx
  - linux
dist: xenial

before_install:
  - cd src

addons:
  homebrew:
    packages:
      - wine

  apt:
    packages:
      - wine

install:
  - npm i
  - npm i electron-packager

script:
  - echo $PATH
  - npm test
  - npm run build
  - codecov

env:
  global:
    # prevent wine popup dialogs about installing additional packages
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"
