sudo: false
language: node_js
node_js:
  - 'node'
os:
  - osx
  - linux
dist: xenial


before_install:
  - cd src

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm i

script:
  - npm test
  - codecov
  - cd ..
  - npm i -g electron-installer-zip electron-installer-dmg electron-packager
  - node utils/building.js