name: 'Build with gulp and lint using ESLint on push'

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: "npm install"
    - run: "npm run build:dev"
    - run: "npm run build:prod"
    - run: "npm run lint:check"